[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.18"
optimizer = true
optimizer_runs = 200
# fs_permissions = [{ access = "read-write", path = "./"}]
fs_permissions = [{ access = "read", path = "./out"}]

ignored_error_codes = ["license", "unused-param", "unused-var"]

[fmt]
line_length = 80

# See more config options https://github.com/foundry-rs/foundry/tree/master/config